### PR TITLE
Update to handsontable 5.0.1

### PR DESCRIPTION
**Pull request by jrowen**
@Paul-A-Kavan, would you mind reviewing this update to `handsontable` v5.0.1 before we merge?

### CODE REVIEW

**Comment by timelyportfolio** [comment]
@jrowen I have been meaning to submit a pull.  I have worked with `5.0.1` with no issues for the last couple of weeks.  Also, there is some new functionality I would like to expose on the `R` side.  I will try to submit a pull over the next couple of weeks.   Thanks so much!

**Comment by jrowen** [comment]
@timelyportfolio That sounds great.  This project has been a bit quiet recently, and it would be great to have some help.

**Comment by Paul-A-Kavan** [comment]
Hey @jrowen I went through lots of the examples you have in the vignette as a starting point. So far things have gone well. I came across an issue with the context menu inside the rstudio viewer when trying to do things like remove rows. I also ran into an issue using the R-parameter approach inside shiny. I was unable to locate the widget instance using the browser console. This relates to #265.  I'll keep going through this as I get time.

**Comment by jrowen** [comment]
@Paul-A-Kavan do these issues look like they're related to the new version of `handsontable` or could they be existing items?

**Comment by Paul-A-Kavan** [comment]
hey @jrowen  I'd like to jump back into helping and I think this branch is holding up progress since future changes will depend on changes that handsontable has made. I did lots of examples a while back and I think the branch is ready to go. 
In the rhandsontable.yaml file it says that we are updating to 5.0.1 which is what the branch was for but based on the handsontable library in lib it looks like you went with 6.1.1 as seen below in a snippet from the handsontable.full.min.js file.
`
* Version: 6.1.1
 * Release date: 23/10/2018 (built at 22/10/2018 12:10:47)
`

**Comment by jrowen** [comment]
You're correct.  The master branch is already on 6.1.1, so this PR no longer applies.

**Pull request closed without merging**
