### PR TITLE
Modify select callback 

### PR DESCRIPTION
**Pull request by Paul-A-Kavan**
Added two arrays to the returned javascript object to include all physical rows and columns that are selected. This then required a custom deserializer to turn the lists into vectors. 
Should fix issue #257

### CODE REVIEW

**Comment by jrowen** [comment]
Could you also regenerate the function documentation and include the updated Rd files? Thanks.

**Comment by Paul-A-Kavan** [comment]
The doc files should be good now.

**Comment by jrowen** [comment]
Thanks.  It looks like the build is failing due to an error with shiny: https://travis-ci.org/jrowen/rhandsontable/jobs/409649314#L1220.  Any ideas why this is happening?

**Comment by jrowen** [comment]
I think the `onload` function is the problem here.  It's assuming `shiny` is available, but we only suggest it in the `DESCRIPTION` file.  I think you'll need to add some error handling (ignore silently if `shiny` not found) to this function to get it to build again.

**Comment by Paul-A-Kavan** [comment]
I added an if statement in .onLoad to check if shiny is installed. Then, if shiny is not installed I throw a warning just to let the user know that the package will have to be reloaded if shiny is installed. I can definitely change the warning message if you'd rather it wasn't included or if you want the wording changed.
The warning is just there to prevent a scenario where a user loads rhandsontable, then installs and loads shiny all in the same session. In this case, the select callback wouldn't be available since the input handler wouldn't have been registered. This might be a case so specific that it isn't worth throwing the error. 
Let me know what changes you'd like me to make!

**Comment by Paul-A-Kavan** [comment]
Oops! I just saw that your comment said to ignore silently. I removed the warning so now it just skips the input handler registration when shiny is not installed.  Sorry about that!

**Comment by jrowen** [comment]
It looks like the build is still failing: https://travis-ci.org/jrowen/rhandsontable/jobs/410138363#L1288.  It appears that the `installed.packages` function isn't available.  Another possible way to handle this could be to wrap the `shiny::...` call in a `tryCatch` function.

**Comment by Paul-A-Kavan** [comment]
I was trying to avoid the general nature of a tryCatch in this specific case but I think you're right! I changed it to a trycatch. 

It might be a good time (after all this hassle) to reconsider the need for the input handler at all. The original goal was to add the selected rows to the selectCallback object that is sent back to R. Without the new event handler the selected rows are returned as sub-lists whereas the natural expectation in R is to receive vectors. The event handler could be removed entirely if we chose to let the user explicitly run unlist() on the returned data lists. I'm starting to think that is a low price to pay for simpler code inside the package. What are your thought, @jrowen?

I think this decision needs to be carefully considered since a future change would cause a compatibility issue for users with code that is written around a particular approach.

**Comment by jrowen** [comment]
It looks like this build is failing.  Did it build locally and were the build checks successful?

**Comment by jrowen** [comment]
This looks great!  Thanks for working through the issues.  One final request before we merge, could you add a brief bullet to the [NEWS](https://github.com/jrowen/rhandsontable/blob/master/NEWS) file that describes the update and fixes?

**Comment by Paul-A-Kavan** [comment]
I added a bullet to the NEWS file for this select callback modification.

**Pull request merged**
