### PR TITLE
Search functionality

### PR DESCRIPTION
**Pull request by ginberg**
Added basic search functionality like it is described on the handsontable page
https://docs.handsontable.com/0.31.2/demo-searching.html

Changes
- upgraded to  handsontable 0.34.5
- added search option to handsontable constructor
- added an [example shiny app](https://ginberg.shinyapps.io/rhandsontable_search/)

### CODE REVIEW

**Comment by jrowen** [comment]
This looks great.  Do you want to add yourself as a contributor to the DESCRIPTION file?  Also, would it make sense to add something to the [doc page](https://jrowen.github.io/rhandsontable/)?

**Comment by ginberg** [comment]
Thanks, I am glad you like it. 
Sure I just added myself as contributor & merged your changes. 

We can add something to the doc page indeed. Shall I do it or do you want to do it? I guess I would just create a link to the example search shiny app

**Comment by jrowen** [comment]
I updated the doc.  Thanks again for submitting.

**Comment by ginberg** [comment]
no problem! Nice that you have created an example via the context menu, I didn't think of that

**Comment by Churongxu** [comment]
When I run the following code, the search function still cannot work on my computer, and my rhandsontable version is the newest
shiny::runGitHub("rhandsontable", "jrowen", 
             subdir="inst/examples/rhandsontable_search")

**Pull request closed without merging**
