### PR TITLE
customRenderer NA values

### PR DESCRIPTION
**Pull request by marciz**

### CODE REVIEW

**Comment by jrowen** [comment]
Would it make sense to add an option to the rhandsontable function that specifies how NA's are treated?  I'm wondering if some may prefer to have NA's shown as empty cells.

**Comment by bklingen** [comment]
I think I want to keep NA's as showing up as empty cells by default.

**Comment by marciz** [comment]
NA are treated as empty by default after #153 
So you dont need specific custom render for NA

**Comment by jrowen** [comment]
Thanks for submitting.  Feel free to submit another PR (or msg me) if you'd like to add yourself as a contributor.

**Pull request merged**
