### PR TITLE
fix search

### PR DESCRIPTION
**Pull request by ginberg**
fix for the search functionality, see [issue](https://github.com/jrowen/rhandsontable/issues/326)

### CODE REVIEW

**Comment by EDiLD** [comment]
@ginberg I tried your version, but can't get it run. Do you have a working example?
`
```r
 rhandsontable(data.frame(a=LETTERS), search = TRUE)
```
gives me no search field

image

Same is also true for rhandsontable from CRAN. :(

**Comment by ginberg** [comment]
@EDiLD the search field only appears if you use it inside a shiny app. Try the [search example](https://github.com/jrowen/rhandsontable/tree/master/inst/examples/rhandsontable_search)

**Comment by jrowen** [comment]
Would you mind adding an update to `NEWS.md` for this update.  Then we should be ready to merge.

**Comment by ginberg** [comment]
hi @jrowen I see you fixed the search issue by yourself already yesterday, including some text in the NEWS.md. We can close this PR

**Comment by jrowen** [comment]
Thanks for contributing.

**Pull request closed without merging**
