### PR TITLE
double reaction in Shiny

### PR DESCRIPTION
**Pull request by marciz**
Not really an elegant solution but avoids double reaction in Shiny when user changes table. Note that there is double reaction once new table is created
Think it solves #216, #137, #271

### CODE REVIEW

**Comment by Paul-A-Kavan** [comment]
I'm not opposed to this solution but I think maybe we need to give the double rendering topic a deeper look since it has been related to so many issues for a while now. @jrowen could you fill me in your current understanding of the issue to get us started? I think I have a limited understanding of the issue currently.

**Comment by marciz** [comment]
I agree the better solution is to add/modify appropriate handsontable events (https://handsontable.com/docs/6.2.2/Hooks.html). But I didn't find any better than currently used `afterChange`

**Comment by lvandersypen** [comment]
When will this pull request be merged and a new release created?  I have a new app which requires several fields to be populated when the user adds the missing ID and the double reaction issue is causing huge problems for me.

**Comment by jrowen** [comment]
Has this fix been effective in addressing the double reaction?

**Comment by marciz** [comment]
@jrowen sorry, I haven't tested it recently

**Comment by shahreyar-abeer** [comment]
I see the issue has been closed.
But the problem persists.

Has it been solved actually?

**Pull request closed without merging**
